// Complete articles data
export const allArticles = [
    {
      id: 1,
      category: 'Planning',
      categoryColor: 'orange',
      title: 'Why your SIP at 25 is worth more than 3× the amount at 35. The math that changes decisions.',
      excerpt: 'Time is a multiplier that no product can match. Here\'s a side-by-side comparison of two investors — same amount, different start dates — and what 10 years does to the outcome.',
      readTime: 'March 2025 · 6 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/sip.jpg',
    },
    {
      id: 2,
      category: 'Fundamentals',
      categoryColor: 'gold',
      title: 'Inflation is a silent tax on <em>idle money.</em> Here\'s how much it\'s costing you.',
      excerpt: '₹10 lakhs today won\'t buy the same things in 10 years. Understanding this is the first step toward building wealth that actually keeps pace with life.',
      readTime: 'Feb 2025 · 4 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/inflation.jpg',
    },
    {
      id: 3,
      category: 'Fundamentals',
      categoryColor: 'gold',
      title: 'You don\'t need 15 mutual funds. You probably need <em>3.</em>',
      excerpt: 'More funds don\'t mean less risk. Over-diversification is its own problem. Here\'s the cleaner way to think about building a portfolio that\'s actually structured.',
      readTime: 'Jan 2025 · 5 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/investment.jpg',
    },
    {
      id: 4,
      category: 'Mindset',
      categoryColor: 'orange',
      title: 'The best investors don\'t time markets. They <em>time their behavior.</em>',
      excerpt: 'Market timing is a losing game. Behavioral timing is everything. Here\'s how to use market volatility to your advantage instead of fighting it.',
      readTime: 'Dec 2024 · 7 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/bestinvestors.jpg',
    },
    {
      id: 5,
      category: 'Planning',
      categoryColor: 'orange',
      title: 'Retirement at 45 isn\'t radical. It\'s just <em>good math.</em>',
      excerpt: 'If you save 50% of your income for 15 years, you can retire. The math is simple. The hard part is the behavior. Here\'s how to bridge that gap.',
      readTime: 'Nov 2024 · 6 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/retirement.jpg',
    },
    {
      id: 6,
      category: 'Fundamentals',
      categoryColor: 'gold',
      title: 'Emergency funds are boring. Until you need one. Here\'s how much you actually need.',
      excerpt: 'The rule of thumb is 6 months. The reality depends on your job security, family structure, and risk tolerance. Let\'s calculate your actual number.',
      readTime: 'Oct 2024 · 5 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/savingsjar.jpg',
    },
    {
      id: 7,
      category: 'Mindset',
      categoryColor: 'orange',
      title: 'The difference between <em>rich</em> and <em>wealthy.</em> It\'s not semantics.',
      excerpt: 'Rich is about income. Wealth is about assets that generate income. One can disappear overnight. The other compounds while you sleep. Here\'s how to build the latter.',
      readTime: 'Sep 2024 · 8 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/rich.jpg',
    },
    {
      id: 8,
      category: 'Planning',
      categoryColor: 'orange',
      title: 'How to think about risk when you\'re 25 vs 45 vs 65. The rules change.',
      excerpt: 'Your risk capacity isn\'t just about age. It\'s about income stability, dependents, and time horizon. Here\'s a framework that evolves with you.',
      readTime: 'Aug 2024 · 6 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/risk.jpg',
    },
    {
      id: 9,
      category: 'Mindset',
      categoryColor: 'orange',
      title: 'The psychology of loss aversion is costing you millions. Here\'s how to fix it.',
      excerpt: 'We feel losses 2x more intensely than gains. This bias keeps us in bad investments and out of good ones. Understanding it is the first step to overcoming it.',
      readTime: 'Jul 2024 · 7 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/psychology.jpg',
    },
    {
      id: 10,
      category: 'Fundamentals',
      categoryColor: 'gold',
      title: 'Asset allocation explained in 3 charts. It\'s simpler than you think.',
      excerpt: '80% of portfolio returns come from asset allocation, not stock selection. Here\'s how to build a portfolio that works for you, without the complexity.',
      readTime: 'Jun 2024 · 5 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/Asset.jpg',
    },
    {
      id: 11,
      category: 'Planning',
      categoryColor: 'orange',
      title: 'The 4% rule is broken. Here\'s what to use instead.',
      excerpt: 'The 4% withdrawal rule was based on outdated assumptions. With longer life expectancies and different market conditions, here\'s a more realistic approach.',
      readTime: 'May 2024 · 6 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/4-rule.jpg',
    },
    {
      id: 12,
      category: 'Mindset',
      categoryColor: 'orange',
      title: 'Why smart people make dumb money mistakes. The behavioral science.',
      excerpt: 'Intelligence doesn\'t protect against cognitive biases. In fact, it can make them worse. Here are the 5 biases that cost smart people the most money.',
      readTime: 'Apr 2024 · 8 min',
      type: 'regular',
      visual: 'image',
      imageSrc: '/smart.png',
    }
  ]
